export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_NEWPRODUCTS: "SET_NEWPRODUCTS",
  SELECTED_PRODCUT: "SELECTED_PRODCUT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  CHANGE_STATE: "CHANGE_STATE",
  COMPELETED_CARTS: "COMPELETED_CARTS",
  UNCOMPELETED_CARTS: "UNCOMPELETED_CARTS",
};
